Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.Sqlite;
using PomoToDoro.Data;
using PomoToDoro.Models;
using PomoToDoro.Models.ViewModels;
using PomoToDoro.Repositories;

namespace PomoToDoro.Controllers;

public class TaskController : Controller
{
    private readonly IRepository _repository;

    public TaskController(IRepository repository)
    {
        _repository = repository;
    }

    public ActionResult Index()
    {
        var todoListViewModel = GetAllTasks();
        return View(todoListViewModel.TaskList);
    }
    
    public ActionResult IndexDone()
    {
        var todoListViewModel = GetAllDoneTasks();
        return View(todoListViewModel.TaskList);
    }
    
    internal TaskViewModel GetAllTasks()
    {
        List<TaskModel> taskList = new();

        using (SqliteConnection con = new SqliteConnection("Data Source=PomoToDoroDB.sqlite"))
        {
            using (var tableCmd = con.CreateCommand())
            {
                con.Open();
                tableCmd.CommandText = "SELECT * FROM Tasks WHERE IsDone = 0";

                using (var reader = tableCmd.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            taskList.Add(
                                new TaskModel
                                {
                                    TaskId = reader.GetInt32(0),
                                    Name = reader.GetString(1)
                                });
                        }
                    }
                    else
                    {
                        return new TaskViewModel
                        {
                            TaskList = taskList
                        };
                    }
                }
            }
        }
        return new TaskViewModel
        {
            TaskList = taskList
        };
    }
    
    internal TaskViewModel GetAllDoneTasks()
    {
        List<TaskModel> taskList = new();

        using (SqliteConnection con = new SqliteConnection("Data Source=PomoToDoroDB.sqlite"))
        {
            using (var tableCmd = con.CreateCommand())
            {
                con.Open();
                tableCmd.CommandText = "SELECT * FROM Tasks WHERE IsDone = 1";

                using (var reader = tableCmd.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            taskList.Add(
                                new TaskModel
                                {
                                    TaskId = reader.GetInt32(0),
                                    Name = reader.GetString(1)
                                });
                        }
                    }
                    else
                    {
                        return new TaskViewModel
                        {
                            TaskList = taskList
                        };
                    }
                }
            }
        }
        return new TaskViewModel
        {
            TaskList = taskList
        };
    }

    internal TaskModel GetTaskById(int id)
    {
        TaskModel taskModel = _repository.Get(id);
        
        //using (var con =
        //       new SqliteConnection("Data Source=PomoToDoroDB.sqlite"))
        //{
        //    using (var tableCmd = con.CreateCommand())
        //    {
        //        con.Open();
        //        tableCmd.CommandText = $"SELECT * FROM Tasks Where TaskId = '{id}'";
        //        using (var reader = tableCmd.ExecuteReader())
        //        {
        //            if (reader.HasRows)
        //            {
        //                reader.Read();
        //                taskModel.TaskId = reader.GetInt32(0);
        //                taskModel.Name = reader.GetString(1);
        //                taskModel.IsDone = reader.GetBoolean(0);
        //            }
        //            else
        //            {
        //                return taskModel;
        //            }
        //        };
        //    }
        //}
        
        return taskModel;
    }

    public ActionResult Create()
    {
        return View(new TaskModel());
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(TaskModel taskModel){
        using (SqliteConnection con = new SqliteConnection("Data Source=PomoToDoroDB.sqlite")){
            using (var tableCmd = con.CreateCommand()){
                con.Open();
                tableCmd.CommandText = $"INSERT INTO Tasks (name) VALUES ('{taskModel.Name}')";
                try{
                    tableCmd.ExecuteNonQuery();
                }
                catch (Exception ex){
                    Console.WriteLine(ex.Message);
                }
            }
        }
        return RedirectToAction(nameof(Index));
    }

    public ActionResult Delete(int id)
    {
        TaskModel taskModel = GetTaskById(id);
        return View(taskModel);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, TaskModel taskModel)
    {
        _repository.Delete(id);
        
        //using (SqliteConnection con =
        //       new SqliteConnection("Data Source=PomoToDoroDB.sqlite"))
        //{
        //    using (var tableCmd = con.CreateCommand())
        //    {
        //        con.Open();
        //        tableCmd.CommandText = $"DELETE from Tasks WHERE TaskId = '{id}'";
        //        tableCmd.ExecuteNonQuery();
        //    }
        //}
        
        return RedirectToAction(nameof(Index));
    }
    
    public ActionResult DeleteDone(int id)
    {
        TaskModel taskModel = GetTaskById(id);
        return View(taskModel);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteDone(int id, TaskModel taskModel)
    {
        _repository.Delete(id);
        
        //using (SqliteConnection con =
        //       new SqliteConnection("Data Source=PomoToDoroDB.sqlite"))
        //{
        //    using (var tableCmd = con.CreateCommand())
        //    {
        //        con.Open();
        //        tableCmd.CommandText = $"DELETE from Tasks WHERE TaskId = '{id}'";
        //        tableCmd.ExecuteNonQuery();
        //    }
        //}
        
        return RedirectToAction(nameof(IndexDone));
    }
    
    public ActionResult Done(int id)
    {
        using (SqliteConnection con =
               new SqliteConnection("Data Source=PomoToDoroDB.sqlite"))
        {
            using (var tableCmd = con.CreateCommand())
            {
                con.Open();
                tableCmd.CommandText = $"UPDATE Tasks SET IsDone = 1 WHERE TaskId = '{id}'";
                tableCmd.ExecuteNonQuery();
            }
        }
        return RedirectToAction(nameof(Index));
    }
    
    public ActionResult UnDone(int id)
    {
        using (SqliteConnection con =
               new SqliteConnection("Data Source=PomoToDoroDB.sqlite"))
        {
            using (var tableCmd = con.CreateCommand())
            {
                con.Open();
                tableCmd.CommandText = $"UPDATE Tasks SET IsDone = 0 WHERE TaskId = '{id}'";
                tableCmd.ExecuteNonQuery();
            }
        }
        return RedirectToAction(nameof(IndexDone));
    }
}

Controllers/TimerController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PomoToDoro.Models;

namespace PomoToDoro.Controllers;

public class TimerController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public TimerController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - PomoToDoro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/PomoToDoro.styles.css" asp-append-version="true"/>
</head>
<body style="background: aliceblue">
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background: lightblue" >
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PomoToDoro</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Lista zadań</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="IndexDone">Ukończone</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Timer" asp-action="Index">Timer pomodoro</a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer style="background: lightblue" class="border-top footer text-muted bg-blue-200">
    <div class="container">
        &copy; 2022 - PomoToDoro
    </div>
</footer >
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>